global:
  scrape_interval: 10s
  evaluation_interval: 10s
  external_labels:
    monitor: "codelab-monitor"

scrape_configs:
  - job_name: "device3"
    scrape_interval: 20s
    static_configs:
      - targets:
          - "golangsubs3-lnf7enmlqa-uc.a.run.app"
  - job_name: "device2"
    scrape_interval: 20s
    static_configs:
      - targets:
          - "golangsubs2-lnf7enmlqa-uc.a.run.app"
  - job_name: "device1"
    scrape_interval: 20s
    static_configs:
      - targets:
          - "golangsubs1-lnf7enmlqa-uc.a.run.app"
